server.port=8585

server.servlet.context-path=/workintech

management.info.env.enabled=true
management.endpoints.web.exposure.include=info,health,mappings

info.app.name=FSWEB S17D2
info.app.description=Spring Boot Dependency Injection Project
info.app.version=1.0.0